export interface ToolMetadata {
  name: string;
  description: string;
  category: "pdf" | "dev" | "utility" | "design" | "business";
  keywords: string[];
  isActive: boolean;
  icon: string;
}

export const toolsRegistry: Record<string, ToolMetadata> = {
  // ==========================================
  // --- PDF TOOLS ---
  // ==========================================
  "pdf-merger": {
    name: "Professional PDF Merger",
    description: "Merge multiple PDF files into a single, high-quality document securely.",
    category: "pdf",
    keywords: ["pdf merger", "combine pdf", "join pdf tools"],
    isActive: true,
    icon: "🔗",
  },
  "split-pdf": {
    name: "Split PDF Pro",
    description: "Extract specific pages or split a large PDF visually in seconds.",
    category: "pdf",
    keywords: ["split pdf", "extract pages", "cut pdf"],
    isActive: true,
    icon: "✂️",
  },
  "compress-pdf": {
    name: "PDF Compressor Engine",
    description: "Reduce PDF file size quickly right in your browser. 100% private.",
    category: "pdf",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
    isActive: true,
    icon: "🗜️",
  },
  "unlock-pdf": {
    name: "Unlock PDF",
    description: "Remove passwords from your protected PDF files quickly and securely.",
    category: "pdf",
    keywords: ["unlock pdf", "remove password", "decrypt pdf"],
    isActive: true,
    icon: "🔓",
  },
  "protect-pdf": {
    name: "Protect PDF",
    description: "Add a secure password to your PDF file to prevent unauthorized access.",
    category: "pdf",
    keywords: ["protect pdf", "encrypt pdf", "add password pdf"],
    isActive: true,
    icon: "🔒",
  },
  "image-to-pdf": {
    name: "Image to PDF",
    description: "Convert single or multiple JPG/PNG images into a high-quality PDF document.",
    category: "pdf",
    keywords: ["image to pdf", "jpg to pdf", "png to pdf", "convert images"],
    isActive: true,
    icon: "🖼️",
  },
  "watermark-pdf": {
    name: "Add PDF Watermark",
    description: "Apne documents ko secure karne ke liye text watermark add karein.",
    category: "pdf",
    keywords: ["watermark pdf", "add text watermark", "secure pdf"],
    isActive: true,
    icon: "©️",
  },
  "invert-pdf": {
    name: "Invert PDF Colors",
    description: "Dark background wali PDF ko white background mein convert karein.",
    category: "pdf",
    keywords: ["invert pdf", "white background", "pdf color fix"],
    isActive: true,
    icon: "☯️",
  },
  "remove-watermark": {
    name: "Remove PDF Watermark",
    description: "PDF se text watermark hatayein.",
    category: "pdf",
    keywords: ["remove watermark", "delete watermark"],
    isActive: true,
    icon: "🧹",
  }, 
  "pdf-stamper": {
    name: "PDF Stamper",
    description: "Click and add custom stamps like VERIFIED or APPROVED anywhere on your PDF.",
    category: "pdf",
    keywords: ["pdf stamper", "add stamp", "verified stamp", "custom pdf stamp"],
    isActive: true,
    icon: "💮",
  },
  "pdf-editor": {
    name: "Advanced PDF Editor",
    description: "All-in-one visual editor. Add text, erase content with whiteout, and highlight shapes directly on your PDF.",
    category: "pdf",
    keywords: ["pdf editor", "whiteout pdf", "add text to pdf", "edit pdf online"],
    isActive: true,
    icon: "✍️",
  },
  "pdf-to-word": {
    name: "PDF to Word Converter",
    description: "Convert PDF documents to editable Word files.",
    category: "pdf",
    keywords: ["pdf to word", "pdf to doc", "convert pdf to word"],
    isActive: true,
    icon: "📝",
  },
  "pdf-to-excel": {
    name: "PDF to Excel",
    description: "Convert PDF tables to Excel spreadsheets easily.",
    category: "pdf",
    keywords: ["pdf to excel", "convert pdf to excel", "pdf to xlsx"],
    isActive: true,
    icon: "📊",
  },

  // ==========================================
  // --- UTILITY / IMAGE TOOLS ---
  // ==========================================
  "add-name-date": {
    name: "Add Name & Date",
    description: "Apni photo par naam aur date add karein taaki wo form filling ke liye ready rahe.",
    category: "utility",
    keywords: ["add name on photo", "photo editor", "date on photo", "form photo"],
    isActive: true,
    icon: "📅",
  },
  "photo-signature-joiner": {
    name: "Photo Signature Joiner",
    description: "Form bharne ke liye photo aur signature ko ek single image mein merge karein.",
    category: "utility",
    keywords: ["join photo signature", "merge image", "exam form photo"],
    isActive: true,
    icon: "🖇️",
  },
  "english-to-hindi-typing": {
    name: "English to Hindi Typing",
    description: "Type in English and automatically convert to Hindi text using fast phonetic transliteration.",
    category: "utility",
    keywords: ["english to hindi typing", "hindi transliteration", "hindi typing online"],
    isActive: true,
    icon: "🔠",
  },
  "age-calculator": {
    name: "Age Calculator",
    description: "Forms ke liye Date of Birth se exact age (Years, Months, Days) calculate karein.",
    category: "utility",
    keywords: ["age calculator", "calculate age", "dob calculator", "form age"],
    isActive: true,
    icon: "🎂",
  },
  "signature-on-photo": {
    name: "Signature On Photo",
    description: "Photo ke upar directly signature overlay karein (Transparent PNG style).",
    category: "utility",
    keywords: ["signature on photo", "overlay signature", "watermark signature", "self attest"],
    isActive: true,
    icon: "🖋️",
  },
  "image-resizer": {
    name: "Photo & Signature Resizer",
    description: "Forms ke hisaab se image ko exact PX, CM, MM ya INCH dimensions mein resize karein.",
    category: "utility",
    keywords: ["image resizer", "photo resizer", "signature resizer", "resize to cm", "resize pixels"],
    isActive: true,
    icon: "📐",
  },
  "smart-card-maker": {
    name: "Smart Card A4 PSD Maker",
    description: "PAN, Aadhaar, Voter ID jaise documents ko crop karein aur seedha A4 print sheet par perfectly arrange karke PSD download karein.",
    category: "utility",
    keywords: ["id card maker", "aadhaar print", "pan card print", "a4 smart card", "cr80 print format"],
    isActive: true,
    icon: "🪪",
  },
  "omr-sheet-maker": {
    name: "A4 OMR Sheet Generator",
    description: "Coaching aur Mock Tests ke liye 50, 100, 150 ya 200 questions wali print-ready OMR sheet PDF download karein.",
    category: "utility",
    keywords: ["omr maker", "omr sheet generator", "mock test sheet", "print omr a4", "bubble sheet"],
    isActive: true,
    icon: "✅",
  },
  "typing-speed-test": {
    name: "Typing Speed Test Engine",
    description: "SSC, Railway, aur Data Entry exams ke liye apni typing speed (WPM) aur accuracy test karein.",
    category: "utility",
    keywords: ["typing test", "wpm checker", "typing speed calculator", "ssc typing test", "english typing"],
    isActive: true,
    icon: "⌨️",
  },
  "resume-builder": {
    name: "Smart Resume / CV Builder",
    description: "Build professional, ATS-friendly A4 resumes in minutes with Live Preview and high-quality PDF export.",
    category: "utility",
    keywords: ["resume maker", "cv builder", "pdf resume", "job resume generator", "ats friendly cv"],
    isActive: true,
    icon: "📄",
  },
  "biodata-maker": {
    name: "Marriage Biodata Maker",
    description: "Create beautiful, professional marriage biodata profiles in PDF format in just 2 minutes.",
    category: "utility",
    keywords: ["biodata maker", "marriage profile", "shaadi biodata", "matrimonial profile generator"],
    isActive: true,
    icon: "💍",
  },
  "muslim-biodata-maker": {
    name: "Muslim Biodata Maker",
    description: "Create professional Islamic marriage biodata profiles in PDF format.",
    category: "utility",
    keywords: ["muslim biodata", "islamic marriage profile", "shaadi biodata", "matrimonial profile generator"],
    isActive: true,
    icon: "🕌",
  },
  "qr-generator": {
    name: "Mega QR Studio",
    description: "Generate URL, Text, WiFi, and VCard (Contact) QR Codes instantly in High Quality.",
    category: "utility",
    keywords: ["qr generator", "qr code maker", "wifi qr", "vcard qr", "mega qr studio", "barcode maker"],
    isActive: true,
    icon: "📱",
  },
  "p2p-share": {
    name: "P2P Secure Share",
    description: "Send any size file directly between devices without servers. 100% private.",
    category: "utility",
    keywords: ["p2p share", "file transfer", "send large files", "direct transfer", "webrtc"],
    isActive: true,
    icon: "🚀",
  },
  "timer": {
    name: "Stopwatch & Timer",
    description: "Advanced browser-based stopwatch and countdown timer with background sync and alarms.",
    category: "utility",
    keywords: ["timer", "stopwatch", "countdown timer", "browser timer", "alarm timer", "study timer"],
    isActive: true,
    icon: "⏱️",
  },
  "walkie-talkie": {
    name: "Walkie Talkie P2P",
    description: "Free, private, push-to-talk voice chat directly in your browser. No signup required.",
    category: "utility",
    keywords: ["walkie talkie", "p2p voice chat", "real-time communication", "browser voice chat"],
    isActive: true,
    icon: "📻",
  },
  "handwriting-pdf": {
    name: "Handwriting PDF Generator",
    description: "Convert your digital text into realistic handwriting style PDF documents.",
    category: "utility",
    keywords: ["handwriting generator", "font to handwriting", "digital assignment"],
    isActive: true,
    icon: "✍️",
  },
  "image-masker": {
    name: "Masking Tool",
    description: "Redact sensitive information from documents and images.",
    category: "utility",
    keywords: ["redaction", "masking", "hide sensitive info"],
    isActive: true,
    icon: "🫥",
  },

  // ==========================================
  // --- DESIGN TOOLS ---
  // ==========================================
  "passport-psd-maker": {
    name: "A4 Passport PSD Maker",
    description: "A4 paper par 6x7 (42 photos) ka passport size format banayein aur seedha .PSD file download karein.",
    category: "design",
    keywords: ["passport size photo maker", "psd generator", "a4 photo format", "studio photo grid"],
    isActive: true,
    icon: "📸",
  },
  "certificate-maker": {
    name: "Pro Certificate Generator",
    description: "Generate authentic, high-quality landscape certificates for courses and events with PDF/PNG export.",
    category: "design",
    keywords: ["certificate maker", "certificate generator", "award certificate", "course certificate", "event certificate"],
    isActive: true,
    icon: "🎓",
  },
  "stamp-maker": {
    name: "Digital Stamp & Seal Maker",
    description: "Generate professional round seals and rectangle rubber stamps. Download as transparent PNG or printable PDF.",
    category: "design",
    keywords: ["stamp maker", "digital seal", "round stamp generator", "rubber stamp", "company seal"],
    isActive: true,
    icon: "🏵️",
  },
  "photo-studio": {
    name: "Mega Photo Studio",
    description: "Crop, resize, and arrange photos for printing.",
    category: "design",
    keywords: ["photo studio", "crop photo", "resize image", "photo printing"],
    isActive: true,
    icon: "🖼️",
  },
  "photo-enhancer": {
    name: "AI Photo Enhancer",
    description: "Purani, blur ya pixelated photos ko 1-click mein HD banayein.",
    category: "design",
    keywords: ["ai enhancer", "hd photo", "remini clone", "clear image", "restore face"],
    isActive: true,
    icon: "✨",
  },
  "pro-suit-changer": {
    name: "Pro Suit Changer",
    description: "Upload your photo and perfectly fit professional suits for passport size images!",
    category: "design",
    keywords: ["ai suit changer", "photo suit editor", "passport suit", "suit fitter", "manual suit maker"],
    isActive: true,
    icon: "👔",
  },
  "remove-bg": {
    name: "Remove BG",
    description: "Remove background from images instantly. Download as transparent PNG or add custom solid colors.",
    category: "design",
    keywords: ["remove bg", "background eraser", "transparent png", "change image color"],
    isActive: true,
    icon: "🪄",
  },
  "logo-maker": {
    name: "Logo Maker",
    description: "Create simple, elegant brand logos instantly.",
    category: "design",
    keywords: ["logo maker", "branding", "logo generator"],
    isActive: true,
    icon: "🎨",
  },
  "event-invite": {
    name: "Event Invitation Maker",
    description: "Design invitations for weddings, parties, or seminars.",
    category: "design",
    keywords: ["invitation", "cards", "event design"],
    isActive: true,
    icon: "🎉",
  },

  // ==========================================
  // --- BUSINESS & OFFICE SUITE ---
  // ==========================================
  "experience-letter-maker": {
    name: "Experience Letter Maker",
    description: "Generate professional Experience & Relieving Letters with company letterhead formatting and PDF export.",
    category: "business",
    keywords: ["experience letter", "relieving letter", "hr letter format", "work experience certificate"],
    isActive: true,
    icon: "📜",
  },
  "invoice-maker": {
    name: "Pro Invoice Maker",
    description: "Generate professional business invoices with auto-calculated taxes, discounts, and HD PDF export.",
    category: "business",
    keywords: ["invoice generator", "bill maker", "gst invoice", "tax invoice", "business billing"],
    isActive: true,
    icon: "🧾",
  },
  "assignment-cover": {
    name: "Assignment Cover Page Maker",
    description: "Create professional assignment cover pages with academic formatting.",
    category: "business",
    keywords: ["assignment cover", "academic report", "project cover"],
    isActive: true,
    icon: "📄",
  },
  "id-card": {
    name: "ID Card Generator",
    description: "Design and generate professional ID cards for schools and offices.",
    category: "business",
    keywords: ["id card maker", "employee id", "student id"],
    isActive: true,
    icon: "🪪",
  },
  "bonafide-cert": {
    name: "Bonafide Certificate Generator",
    description: "Generate official bonafide certificates with custom branding.",
    category: "business",
    keywords: ["bonafide certificate", "official letter", "proof of study"],
    isActive: true,
    icon: "🎓",
  },
  "tc-generator": {
    name: "TC Generator",
    description: "Create official Transfer Certificates for institutions.",
    category: "business",
    keywords: ["tc generator", "transfer certificate", "school leaving"],
    isActive: true,
    icon: "📜",
  },
  "marksheet-designer": {
    name: "Marksheet Designer",
    description: "Professional marksheet generator with auto-calculation engine.",
    category: "business",
    keywords: ["marksheet generator", "report card", "exam results"],
    isActive: true,
    icon: "📊",
  },
  "admit-card": {
    name: "Admit Card Designer",
    description: "Create secure admit cards with QR/Barcode and exam details.",
    category: "business",
    keywords: ["admit card", "hall ticket", "exam card"],
    isActive: true,
    icon: "🛡️",
  },
  "affidavit-gen": {
    name: "Affidavit Generator",
    description: "Generate legal affidavits for various purposes.",
    category: "business",
    keywords: ["affidavit", "legal document", "stamp paper"],
    isActive: true,
    icon: "⚖️",
  },
  "receipt-maker": {
    name: "Receipt/Invoice Maker",
    description: "Smart billing tool with auto-tax and discount calculation.",
    category: "business",
    keywords: ["receipt generator", "invoice maker", "billing"],
    isActive: true,
    icon: "🧾",
  },
  "cover-letter": {
    name: "Cover Letter Generator",
    description: "Tailored professional cover letters for job applications.",
    category: "business",
    keywords: ["cover letter", "job application", "resume tool"],
    isActive: true,
    icon: "✉️",
  },
  "quotation-maker": {
    name: "Quotation Maker",
    description: "Generate professional business estimates and proposals.",
    category: "business",
    keywords: ["quotation", "price estimate", "proposal"],
    isActive: true,
    icon: "📝",
  },
  "letterhead-maker": {
    name: "Letterhead Maker",
    description: "Professional corporate letterhead builder with 10+ templates.",
    category: "business",
    keywords: ["letterhead", "corporate design", "stationery"],
    isActive: true,
    icon: "🏢",
  },
  "visiting-card": {
    name: "Visiting Card Maker",
    description: "Create stunning business cards with 625+ design variations.",
    category: "business",
    keywords: ["business card", "visiting card", "branding"],
    isActive: true,
    icon: "💳",
  },
  "business-profile": {
    name: "Business Profile Generator",
    description: "Generate a formal corporate profile and mission pitch.",
    category: "business",
    keywords: ["business profile", "company pitch", "corporate identity"],
    isActive: true,
    icon: "💼",
  },
  "salary-slip": {
    name: "Salary Slip Generator",
    description: "Generate professional monthly salary slips for employees.",
    category: "business",
    keywords: ["salary slip", "payslip", "payroll"],
    isActive: true,
    icon: "💰",
  },
  "email-signature": {
    name: "Email Signature Generator",
    description: "Create professional email signatures with social links.",
    category: "business",
    keywords: ["email signature", "branding", "professional email"],
    isActive: true,
    icon: "✒️",
  }
};